### ISSUE TITLE
Guidelines for groupGeneric methods?

### ISSUE THREAD

**Issue by richfitz** [wch/R6#29]
Is there a recommended way of creating things to dispatch on things like math operations (*, /, +, -)?  Or on subset operations (e.g. '[')?  Is creating an S3 method and forwarding to an R6 method the best way of doing this?

**Comment by wch** [comment]
As far as I know, the best thing to do is just to create S3 methods for this.

I've actually run into some issues in the past with "Incompatible methods" when using S3 dispatch for operators, and this finally pushed me to write up the problem, and a solution. Here it is: https://github.com/wch/s3ops

**Comment by richfitz** [comment]
Thanks, that's super useful.
