### ISSUE TITLE
names() for R6

### ISSUE THREAD

**Issue by kablag** [wch/R6#30]
As I understand for now names(R6) returns NULL.
I think it's usefull to add S3 method names() for R6, because, for example, RStudio use this method to get names for autocompletion at editor.
Returning of public fields and methods names can be easily implemented by:
```
names.R6 <- function(object) {
  ls(object)
}
```

**Comment by wch** [comment]
Closing for now. After looking into a bit more, here's my thinking: There's a semantic difference between `names()` on one hand, and `objects()`/`ls()` on the other, and `names()` isn't quite right for R6 objects.

The `names()` function is meant to operate on objects that have items in a particular order, like lists and vectors. The `objects()`/`ls()` functions are meant to operate on environments, which don't have items in a particular order.

It's true that you can do `ls(list(b=1, a=2))`, but that only works by coercing the list to an environment first. If you do this, the order of the output won't match the input:

```R
ls(list(b=1, a=2))
# [1] "a" "b"

names(list(b=1, a=2))
[1] "b" "a"
```

R6 objects are environments underneath, and as such don't have an order to the items, so `names()` isn't quite right.

This also happens to align with my goal of keeping the R6 package minimal. :)


As for adding the `environment` class, the only `.environment` method that I could find in base R is `as.list.environment`. Adding the class doesn't seem worth it, given that there's a small performance penalty for the extra S3 dispatch, and only one function for which it matters.

```R
x <- pryr::rls(parent.env(parent.env(globalenv())))
x <- unlist(x)
x[grepl('.environment', x, fixed = TRUE)]
# [1] ".__C__.environment"  "as.environment"      "as.list.environment"
# [4] "is.environment"     

# Of these, only as.list.environment is an S3 method
```

**Comment by kevinushey** [comment]
It's worth noting that latest versions of R-devel now provide a facility for custom completions: https://github.com/wch/r-source/commit/b0e708ddf5ab5f2da1910b9776b82f6c1f7b24f8

Perhaps this is something that R6 could (eventually) provide for completions outside of RStudio?

**Comment by wch** [comment]
Interesting, thanks for the pointer!
