### ISSUE TITLE
Strange singleton issue

### ISSUE THREAD

**Issue by robertzk** [wch/R6#68]
I am having a very bizarre issue. I have a complicated R6 class called `director` that is being subclassed in another package, where it is called `engine` (so `director` is portable in package A and `engine` inherits from `director` in package B). I see the following behavior.

```r
> engine_class$new("~/dev/modeling.sy") -> b
> b
Director object monitoring ‘/Users/robertk/dev/modeling.sy’.
> engine_class$new("~/dev/base.sy") -> s
> s
Director object monitoring ‘/Users/robertk/dev/base.sy’.
> b
Director object monitoring ‘/Users/robertk/dev/base.sy’.
```

Should I look further into my `director` object definition and strive to produce a minimal reproducible example, or could this be an R6 issue, and do you have any ideas for how to start debugging this?

**Comment by robertzk** [comment]
My R version is 3.0.2 and my R6 version is 2.1.0.

**Comment by robertzk** [comment]
I have replicate the issue in the simplest case when

```r
engine_class <- R6::R6Class("engine", portable = TRUE, inherits = director:::director_)
```

**Comment by wch** [comment]
Do any of the fields in `director_` contain reference objects? Might be related to this:
  https://cran.r-project.org/web/packages/R6/vignettes/Introduction.html#fields-containing-reference-objects.

**Comment by robertzk** [comment]
Interesting! I did not know about that behavior, although that was not it. I was actually refactoring `director_` from refClass to R6, and it seems I forgot a few `self` references, so it was setting global variables instead! 

Thanks for the fast response.

**Comment by robertzk** [comment]
It makes sense to store the initial default values in the R6 definition, so the reference-type member initializer issue makes sense; reminds me of the care needed around python default arguments.

**Comment by wch** [comment]
Oh yeah, I've been bitten by the `<<-` assignment before.
