### ISSUE TITLE
overriding [[ for R6 class breaks print

### ISSUE THREAD

**Issue by piccolbo** [wch/R6#70]
because this R6 class represent a collection with its own contents, but the print method loops over obj_names and then passes each of them to [[. I know I can override print and it's already planned, but if I were fine with the default print, is there a way to avoid this? And is this an isolated instance or am I going to break other things?

**Comment by wch** [comment]
I just pushed a fix. Can you test it out and report back? Thanks!

**Comment by piccolbo** [comment]
Problem solved. Thanks
