### ISSUE TITLE
do.call for class methods

### ISSUE THREAD

**Issue by terrytangyuan** [wch/R6#83]
For example, I have a `Class1$addKV("key1", "value1")` function. Is there a way to use `do.call()` to call it since I want to make this more general. 

Thanks!

**Comment by wch** [comment]
You can use `do.call(Class1$addKV, list("key1", "value1"))`.

**Comment by terrytangyuan** [comment]
Sure, I meant something like this `do.call("AnyClassName$addKV", list("key1", "value1"))`.

**Comment by wch** [comment]
It depends on which part you want to be a string. If it's the object:

```R
objName <- "AnyClassName"

obj <- get(objName)
do.call(obj$addKV, list("key", "value"))
```

If it's the method:

```R
methodName <- "addKV"

do.call(obj[[methodName]], list("key", "value"))
```

If you want to use a single string for both, you could use `eval`, although it's a little gross:

```R
f <- eval("AnyClassName$addKV")
do.call(f, list("key", "value"))
```

**Comment by terrytangyuan** [comment]
Got it! This is very helpful! Thanks!

**Comment by wch** [comment]
Oops, the eval code should be:

```R
f <- eval(parse(text = "AnyClassName$addKV"))
```

**Comment by terrytangyuan** [comment]
Yep got the idea! Thanks!
