### ISSUE TITLE
Finalizers

### ISSUE THREAD

**Issue by gaborcsardi** [wch/R6#92]
I know I can use `reg.finalizer`, in `initialize` or on the object, but what do you think about making finalizers more explicit, i.e. having a special `finalize` method?

It should not be too hard with `reg.finalizer`. We just check if there is a `finalize` method at object creation, and if there is, we call `reg.finalizer` on it.

**Comment by wch** [comment]
Sounds like a good idea to me!

**Comment by gaborcsardi** [comment]
OK, I'll put together a PR.
